# Generated by Django 3.2.5 on 2021-12-19 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewAccount',
            fields=[
                ('account_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('account_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('account_type', models.CharField(choices=[('LOAN', 'Loan'), ('SAVING-BANK', 'Saving-Bank'), ('CURRENT-BANK', 'Current-Bank'), ('PETTY CASH', 'Petty Cash'), ('MOBILE WALLET', 'Mobile Wallet'), ('UPI WALLET', 'UPI Wallet')], default='', max_length=255)),
                ('opening_balance', models.FloatField()),
                ('current_balance', models.FloatField()),
            ],
        ),
    ]
