# Generated by Django 3.2.5 on 2021-12-19 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_newexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewDepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
    ]
