# Generated by Django 3.2.5 on 2021-12-21 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_newdepart'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('amount', models.FloatField()),
                ('expense_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.newexpense')),
                ('paid_from_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.newaccount')),
            ],
        ),
    ]
