# Generated by Django 3.2.5 on 2021-12-21 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_hrexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiscExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('expense_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.newexpense')),
                ('paid_from_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.newaccount')),
                ('purpose', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.hrexpense')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
