# Generated by Django 3.2.5 on 2021-12-21 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_miscexpenses'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenerateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('account_number', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.newaccount')),
                ('department_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.newdepart')),
                ('expense_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.newexpense')),
                ('item_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.itemexpense')),
            ],
        ),
    ]
